const BASE = "http://localhost:3000";

export {};

const DATA: { name: string; summary: string; category: string; metadata?: Record<string, unknown> }[] = [
  { name: "Bangkok is the capital", summary: "Bangkok, the capital of Thailand, is one of the world's most visited cities with over 20 million visitors a year.", category: "travel" },
  { name: "Thai currency", summary: "The Thai currency is the baht (THB). Coins come in satang denominations and notes range from 20 to 1,000 baht.", category: "cost of living" },
  { name: "The Thai greeting", summary: "The wai is Thailand's traditional greeting, performed with palms pressed together and a slight bow.", category: "culture" },
  { name: "Thailand never colonized", summary: "Thailand is the only Southeast Asian country never colonized by a European power, formerly known as Siam.", category: "history" },
  { name: "Pad Thai noodles", summary: "Pad Thai is Thailand's most famous noodle dish, made with rice noodles, egg, tofu, shrimp, and tamarind sauce.", category: "food" },
  { name: "Tom Yum Goong", summary: "Tom Yum Goong is a hot and sour Thai soup with shrimp, lemongrass, galangal, and chili.", category: "food" },
  { name: "Thai green curry", summary: "Green curry is a creamy Thai curry made with coconut milk, green chili paste, basil, and chicken or beef.", category: "food" },
  { name: "Som Tam papaya salad", summary: "Som Tam is a spicy shredded green papaya salad with peanuts, lime, fish sauce, and chili.", category: "food" },
  { name: "Mango sticky rice", summary: "Mango sticky rice is a classic Thai dessert made with glutinous rice, fresh mango, and coconut cream.", category: "food" },
  { name: "Thai street food culture", summary: "Thailand's street food scene is legendary, offering cheap, fresh meals from market stalls across every city.", category: "food" },
  { name: "Khao Pad fried rice", summary: "Khao Pad is Thai-style fried rice typically served with cucumber, lime, and nam pla fish sauce.", category: "food" },
  { name: "Thai iced tea", summary: "Cha yen, Thai iced tea, is a sweet orange tea with condensed milk served over ice, popular with expats.", category: "food" },
  { name: "Massaman curry", summary: "Massaman curry is a rich Thai-Muslim curry influenced by Persian and Indian spices, often made with beef or chicken.", category: "food" },
  { name: "Pad Kra Pao", summary: "Pad Kra Pao is a stir-fried basil dish with minced meat, garlic, chili, and a fried egg on top.", category: "food" },
  { name: "Dining etiquette", summary: "In Thailand, the fork is used to push food onto the spoon, and the spoon is the primary eating utensil.", category: "culture" },
  { name: "Buddhist majority", summary: "Over 90% of Thais are Buddhist, and temples, or wats, are central to daily life across the country.", category: "culture" },
  { name: "Songkran water festival", summary: "Songkran, in mid-April, is Thailand's New Year festival famous for nationwide water fights and blessing rituals.", category: "culture" },
  { name: "Loy Krathong festival", summary: "Loy Krathong is a November festival where people float decorated baskets on rivers and release sky lanterns.", category: "culture" },
  { name: "Thai monarchy", summary: "Thailand is a constitutional monarchy and the Thai royal family is deeply revered across the country.", category: "culture" },
  { name: "Bangkok traffic", summary: "Bangkok is notorious for heavy traffic, so the BTS Skytrain and MRT are the fastest ways to get around.", category: "transport" },
  { name: "Tuk-tuks in Bangkok", summary: "Tuk-tuks are three-wheeled taxis in Bangkok, fun for short trips but often pricier than metered taxis.", category: "transport" },
  { name: "Grab ridesharing", summary: "Grab is the dominant ridesharing app in Thailand, offering cars, motorbikes, and food delivery.", category: "transport" },
  { name: "Songthaew trucks", summary: "Songthaews are shared pickup-truck taxis common in Chiang Mai and upcountry Thailand, with fixed cheap fares.", category: "transport" },
  { name: "Motorcycle taxis", summary: "Motorcycle taxis with colored vests are fast and convenient for short Bangkok trips, but always agree on the fare.", category: "transport" },
  { name: "Thai railways", summary: "Thailand's State Railway connects Bangkok with Chiang Mai, the northeast, and the south at very low cost.", category: "transport" },
  { name: "Airport rail link", summary: "The Airport Rail Link connects Suvarnabhumi Airport to downtown Bangkok in about 30 minutes.", category: "transport" },
  { name: "Chiang Mai old city", summary: "Chiang Mai's old city is a moated, walled historic center packed with over 30 ancient Buddhist temples.", category: "travel" },
  { name: "Phuket beaches", summary: "Phuket is Thailand's largest island, known for Patong's nightlife and quieter beaches like Kata and Karon.", category: "travel" },
  { name: "Krabi limestone cliffs", summary: "Krabi is famous for dramatic limestone karsts, Railay beach, and world-class rock climbing.", category: "travel" },
  { name: "Koh Samui", summary: "Koh Samui is a Gulf of Thailand island with coconut palm beaches, waterfalls, and luxury resorts.", category: "travel" },
  { name: "Koh Phi Phi", summary: "Koh Phi Phi is a stunning island archipelago made famous by the movie The Beach, reached by ferry from Phuket.", category: "travel" },
  { name: "Ayutthaya ruins", summary: "Ayutthaya, a former Siamese capital, is a UNESCO site of ancient temple ruins one hour from Bangkok.", category: "travel" },
  { name: "Sukhothai historical park", summary: "Sukhothai Historical Park preserves the ruins of Thailand's first capital, dating to the 13th century.", category: "travel" },
  { name: "Grand Palace Bangkok", summary: "The Grand Palace in Bangkok, with the Emerald Buddha temple, is the city's most visited landmark.", category: "travel" },
  { name: "Khao San Road", summary: "Khao San Road is Bangkok's famous backpacker street with budget hostels, street food, and nightlife.", category: "travel" },
  { name: "Pattaya", summary: "Pattaya is a beach resort city two hours from Bangkok, known for its nightlife and seafood.", category: "travel" },
  { name: "Hua Hin", summary: "Hua Hin is a royal seaside resort town on the Gulf of Thailand, popular with families and retirees.", category: "travel" },
  { name: "Isan northeast region", summary: "Isan, Thailand's northeast, offers rural charm, Khmer ruins, and spicy dishes like larb and som tam.", category: "travel" },
  { name: "National parks", summary: "Thailand has over 150 national parks including Khao Yai, Doi Inthanon, and the marine parks of the Andaman coast.", category: "travel" },
  { name: "Thai elephants", summary: "Thailand is home to thousands of elephants, with ethical sanctuaries offering expats a chance to volunteer.", category: "wildlife" },
  { name: "Long-tailed boats", summary: "Long-tail boats are the classic Thai river boats used to reach islands and floating markets.", category: "transport" },
  { name: "Floating markets", summary: "Floating markets like Damnoen Saduak sell fruit and souvenirs from wooden boats on Bangkok's canals.", category: "travel" },
  { name: "Thai silk", summary: "Thai silk, especially from the northeast, is world-famous for its quality and is a top export and souvenir.", category: "shopping" },
  { name: "Night markets", summary: "Thai night markets, such as Chiang Mai's Sunday walking street, are great for food, crafts, and bargains.", category: "shopping" },
  { name: "Chatuchak weekend market", summary: "Chatuchak in Bangkok is one of the world's largest markets with over 15,000 stalls open on weekends.", category: "shopping" },
  { name: "711 convenience stores", summary: "Thailand has over 12,000 7-Eleven stores offering meals, phone top-ups, and everyday essentials.", category: "lifestyle" },
  { name: "Thai healthcare quality", summary: "Thailand is a leading medical tourism destination with world-class private hospitals at low cost.", category: "healthcare" },
  { name: "Bumrungrad hospital", summary: "Bumrungrad International Hospital in Bangkok treats over a million international patients annually.", category: "healthcare" },
  { name: "Thailand expat insurance", summary: "Expats usually buy private health insurance in Thailand, as local insurance covers public care but often not private hospitals.", category: "healthcare" },
  { name: "Medical tourism", summary: "Thailand attracts over 2 million medical tourists a year for dental work, cosmetic surgery, and check-ups.", category: "healthcare" },
  { name: "Thai pharmacies", summary: "Pharmacies are plentiful in Thailand and many common medications are sold without a prescription.", category: "healthcare" },
  { name: "Thai massage", summary: "Thai massage is a centuries-old therapy blending acupressure and assisted stretching, available everywhere.", category: "lifestyle" },
  { name: "Muay Thai boxing", summary: "Muay Thai, Thai boxing, is the national sport and a popular fitness and spectator activity in Thailand.", category: "lifestyle" },
  { name: "Thai beaches", summary: "Thailand has over 1,500 miles of coastline with some of the world's most beautiful tropical beaches.", category: "travel" },
  { name: "Scuba diving", summary: "Thailand offers world-class scuba diving, especially around Koh Tao, Similan Islands, and Richelieu Rock.", category: "travel" },
  { name: "Thai islands count", summary: "Thailand has more than 1,400 islands, though only a fraction are developed or inhabited.", category: "travel" },
  { name: "Thai language tones", summary: "Thai is a tonal language with five tones, which makes learning it challenging but rewarding for expats.", category: "language" },
  { name: "Thai alphabet", summary: "The Thai alphabet has 44 consonants and 32 vowels, written left to right without spaces between words.", category: "language" },
  { name: "Useful Thai phrases", summary: "Useful Thai phrases include sawasdee (hello), kop khun (thank you), and mai pen rai (no worries).", category: "language" },
  { name: "Thai nicknames", summary: "Almost all Thais have a short nickname, usually in English, used by friends and colleagues.", category: "culture" },
  { name: "Saving face culture", summary: "Thais avoid open conflict to preserve face, so criticism is usually delivered gently and indirectly.", category: "culture" },
  { name: "The land of smiles", summary: "Thailand is nicknamed the Land of Smiles because of the importance of politeness and friendliness.", category: "culture" },
  { name: "Thai politeness particles", summary: "Thai speakers add the polite particles khrap (men) and kha (women) at the end of sentences.", category: "language" },
  { name: "Chakri dynasty", summary: "The current Thai royal house, the Chakri dynasty, has reigned since the founding of Bangkok in 1782.", category: "history" },
  { name: "Sukhothai kingdom", summary: "The Sukhothai Kingdom, founded in 1238, is considered the cradle of Thai culture and script.", category: "history" },
  { name: "World War II Thailand", summary: "Thailand was allied with Japan in World War II but the Free Thai movement worked with the Allies.", category: "history" },
  { name: "Thai economy", summary: "Thailand's economy is the second largest in Southeast Asia, powered by tourism, manufacturing, and exports.", category: "cost of living" },
  { name: "Thai agriculture", summary: "Thailand is the world's largest rice exporter and a top producer of rubber, sugar, and tropical fruit.", category: "cost of living" },
  { name: "Minimum wage Thailand", summary: "Thailand's daily minimum wage ranges from about 330 to 370 baht depending on the province.", category: "cost of living" },
  { name: "Bangkok rent", summary: "A modern one-bedroom condo in central Bangkok typically rents for 15,000 to 30,000 baht a month.", category: "cost of living" },
  { name: "Chiang Mai rent", summary: "Chiang Mai offers much cheaper rent, with one-bedroom condos often available for 8,000 to 15,000 baht monthly.", category: "cost of living" },
  { name: "Utility costs Thailand", summary: "Monthly electricity for a condo in Thailand typically runs 1,500 to 3,000 baht, plus modest water bills.", category: "cost of living" },
  { name: "Food costs Thailand", summary: "Eating out is cheap in Thailand, with street meals costing 40 to 80 baht and casual restaurant meals 100 to 300 baht.", category: "cost of living" },
  { name: "Grocery costs", summary: "Western groceries from import stores like Villa or Gourmet Market cost more, while local markets are very cheap.", category: "cost of living" },
  { name: "Digital nomad lifestyle", summary: "Thailand is a top digital nomad destination, though the government now restricts remote work visas.", category: "lifestyle" },
  { name: "Long-term visas", summary: "Expats can stay long-term via retirement, marriage, business, elite, or LTR visas in Thailand.", category: "visa" },
  { name: "Thailand retirement visa", summary: "The O-A retirement visa suits expats over 50, requiring 800,000 baht in the bank or a 65,000 baht monthly income.", category: "visa" },
  { name: "Thailand Elite visa", summary: "The Elite visa grants 5 to 20 year stays starting around 600,000 baht, with VIP airport perks.", category: "visa" },
  { name: "LTR visa Thailand", summary: "The Long-Term Resident visa offers 10-year stays for high earners, retirees, and remote workers.", category: "visa" },
  { name: "Thai work permit", summary: "Foreigners need a work permit in Thailand even for simple jobs; working without one is illegal.", category: "visa" },
  { name: "90-day reporting", summary: "Foreigners on long-term visas must report their address to immigration every 90 days.", category: "visa" },
  { name: "Thai bank account", summary: "Expats can open a Thai bank account with a passport, visa, and proof of residence or a work permit.", category: "lifestyle" },
  { name: "Banking in Thailand", summary: "Top Thai banks include Bangkok Bank, Kasikorn, SCB, and Krungthai, all with English-speaking branches.", category: "lifestyle" },
  { name: "Thai SIM cards", summary: "Expats can buy Thai SIM cards from AIS, True, and dtac with cheap data plans, using passport registration.", category: "lifestyle" },
  { name: "Thailand internet", summary: "Home fiber internet in Thailand is fast and cheap, often 1 Gbps for under 1,000 baht a month.", category: "lifestyle" },
  { name: "Thai weather hot season", summary: "Thailand's hot season runs March to May, with April temperatures often exceeding 40 degrees Celsius.", category: "weather" },
  { name: "Thai rainy season", summary: "The rainy season from June to October brings daily downpours, mostly in the afternoon.", category: "weather" },
  { name: "Thai cool season", summary: "The cool season from November to February is the most comfortable time for expats in Thailand.", category: "weather" },
  { name: "Northern Thailand cold", summary: "Mountain towns in northern Thailand like Pai and Doi Inthanon can drop below 10 degrees Celsius in winter.", category: "weather" },
  { name: "Monsoon seasons", summary: "Thailand has two monsoons, the southwest bringing rain to the Andaman coast and the northeast to the Gulf.", category: "weather" },
  { name: "Wat temples everywhere", summary: "There are over 40,000 Buddhist temples in Thailand, from golden Bangkok wats to forest temples in the north.", category: "culture" },
  { name: "Big Buddha Phuket", summary: "The Big Buddha of Phuket is a 45-meter white marble statue overlooking the island from Nakkerd Hill.", category: "travel" },
  { name: "Doi Suthep", summary: "Wat Phra That Doi Suthep is a sacred mountain temple in Chiang Mai reached by 306 golden steps.", category: "travel" },
  { name: "Thai New Year April", summary: "Thai New Year falls on April 13 each year and is celebrated with water as a symbol of cleansing.", category: "culture" },
  { name: "Songkran water fight", summary: "During Songkran, cities across Thailand hold massive water fights and Thais sprinkle water on elders as respect.", category: "culture" },
  { name: "Kings birthday", summary: "The King's birthday in late July is also Father's Day in Thailand, celebrated with lights and candles.", category: "culture" },
  { name: "Vegetarian festival", summary: "The Phuket Vegetarian Festival in October sees devotees performing extreme acts of devotion while eating vegan food.", category: "culture" },
  { name: "Thai Buddhist monks", summary: "Many Thai men become monks temporarily, traditionally for weeks or months, as a rite of passage.", category: "culture" },
  { name: "Respect for monks", summary: "In Thailand, never touch a monk, and women should avoid direct contact or handing things to them.", category: "culture" },
  { name: "Temple dress code", summary: "Visitors must cover shoulders and knees when entering Thai temples; shoes must always be removed.", category: "culture" },
  { name: "Never disrespect the king", summary: "Lèse-majesté laws in Thailand make insulting the monarchy a serious criminal offense.", category: "culture" },
  { name: "Thai head and feet", summary: "In Thai culture the head is considered sacred and the feet lowly; never touch someone's head or point with your feet.", category: "culture" },
  { name: "Buddha images sacred", summary: "Buddha images are sacred in Thailand and it is illegal to take them out of the country without permission.", category: "culture" },
  { name: "Sathing food spicy", summary: "Thai food is famously spicy, and locals say mai phet (not spicy) to ask for mild versions.", category: "food" },
  { name: "Durian fruit", summary: "Durian, the pungent king of fruits, is a Thai favorite and banned in many hotels and airports.", category: "food" },
  { name: "Thai coconuts", summary: "Thailand is one of the world's largest coconut producers, used in cooking, drinks, and cosmetics.", category: "food" },
  { name: "Rambutan fruit", summary: "Rambutan, with its hairy red shell, is a sweet tropical fruit popular in Thai markets.", category: "food" },
  { name: "Mangosteen fruit", summary: "Mangosteen is called the queen of fruits and is prized in Thailand for its sweet white segments.", category: "food" },
  { name: "Thai coffee culture", summary: "Thailand's northern highlands produce quality arabica coffee, fueling a growing cafe culture in Chiang Mai.", category: "food" },
  { name: "Singha and Chang beer", summary: "Singha and Chang are the best-known Thai lagers, widely drunk with spicy meals across the country.", category: "food" },
  { name: "Thai street BBQ", summary: "Thai moo ping, grilled pork skewers, and satay are quick, cheap street food staples.", category: "food" },
  { name: "Thai desserts sweet", summary: "Thai desserts like khao niew mamuang (mango sticky rice) and luk chup are sweet and often coconut-based.", category: "food" },
  { name: "Yakult in Thailand", summary: "Yakult and local probiotic drinks are sold at every Thai convenience store and market.", category: "food" },
  { name: "Thai meal balance", summary: "A traditional Thai meal balances sweet, sour, salty, and spicy flavors in one table spread.", category: "food" },
  { name: "Rice is staple", summary: "Jasmine rice is the staple of Thai meals, usually eaten with several shared dishes.", category: "food" },
  { name: "Thai cooking fresh", summary: "Thai cooking relies on fresh herbs like lemongrass, kaffir lime, galangal, and Thai basil.", category: "food" },
  { name: "Fisherman villages", summary: "Coastal Thai fishing villages supply the country's seafood and are a highlight of island travel.", category: "travel" },
  { name: "Koh Lanta chill", summary: "Koh Lanta is a laid-back Andaman island popular with families and long-stay travelers.", category: "travel" },
  { name: "Koh Chang island", summary: "Koh Chang, near the Cambodian border, is a large, jungle-covered island with quiet beaches.", category: "travel" },
  { name: "Khao Sok park", summary: "Khao Sok National Park features ancient rainforest, limestone mountains, and Cheow Lan Lake.", category: "travel" },
  { name: "Erawan falls", summary: "Erawan Falls in Kanchanaburi is a stunning seven-tiered turquoise waterfall near Bangkok.", category: "travel" },
  { name: "Bridge over River Kwai", summary: "The famous Bridge over the River Kwai in Kanchanaburi was built during World War II.", category: "travel" },
  { name: "Golden Triangle", summary: "The Golden Triangle where Thailand, Laos, and Myanmar meet is a historic opium-producing region.", category: "travel" },
  { name: "Thai border crossings", summary: "Thailand shares borders with Myanmar, Laos, Cambodia, and Malaysia, with many land crossings.", category: "travel" },
  { name: "Similan Islands diving", summary: "The Similan Islands are among the world's top diving destinations with clear water and coral reefs.", category: "travel" },
  { name: "Whale watching", summary: "Whale watching off Thailand's coast is possible, with sightings of Bryde's whales near Samui.", category: "wildlife" },
  { name: "Sea turtles Thailand", summary: "Thailand's marine parks protect sea turtles, which nest on islands like Koh Phra Thong.", category: "wildlife" },
  { name: "Birds in Thailand", summary: "Thailand is a birdwatcher's paradise with over 1,000 bird species across its varied habitats.", category: "wildlife" },
  { name: "Thai king cobra", summary: "The king cobra, one of the world's longest venomous snakes, lives in Thailand's forests.", category: "wildlife" },
  { name: "Tigers in Thailand", summary: "Small populations of Indochinese tigers still roam Thailand's western forest reserves.", category: "wildlife" },
  { name: "Hornbills", summary: "Thailand's hornbills, including the great hornbill, thrive in Khao Yai and southern forests.", category: "wildlife" },
  { name: "Orchid varieties", summary: "Thailand is home to over 1,500 native orchid species, and the orchid is part of Thai cultural life.", category: "wildlife" },
  { name: "Rubber plantations", summary: "Southern Thailand's rubber plantations make the country one of the world's top natural rubber producers.", category: "cost of living" },
  { name: "Palm oil farms", summary: "Thailand grows oil palms across the south, an important agricultural export crop.", category: "cost of living" },
  { name: "Thai fishing industry", summary: "Thailand is among the world's largest seafood exporters, with major fishing ports in the south.", category: "cost of living" },
  { name: "Auto manufacturing", summary: "Thailand is a major car manufacturing hub, sometimes called the Detroit of Asia.", category: "cost of living" },
  { name: "Thai tourism economy", summary: "Tourism contributes roughly a fifth of Thailand's GDP, making it vital to the national economy.", category: "cost of living" },
  { name: "Thailand timezone", summary: "Thailand is on ICT time, seven hours ahead of UTC, and does not observe daylight saving time.", category: "lifestyle" },
  { name: "Emergency number 191", summary: "The general emergency number in Thailand is 191, and 1155 is the tourist police hotline.", category: "lifestyle" },
  { name: "Driving in Thailand", summary: "Thailand drives on the left-hand side of the road, and international licenses are accepted for short stays.", category: "lifestyle" },
  { name: "Thai driver's license", summary: "Long-term residents can exchange or apply for a Thai driver's license at the Land Transport office.", category: "lifestyle" },
  { name: "Thailand public holidays", summary: "Thailand has about 20 public holidays a year, including Buddhist days and royal ceremonies.", category: "culture" },
  { name: "Thai working hours", summary: "Typical Thai office hours run from 9am to 6pm, with a one-hour lunch break.", category: "lifestyle" },
  { name: "Tipping in Thailand", summary: "Tipping is not mandatory in Thailand, but leaving small change at restaurants is common practice.", category: "culture" },
  { name: "Bargaining culture", summary: "Bargaining is expected at markets and street stalls in Thailand, but not in shops or malls.", category: "shopping" },
  { name: "Thai honesty", summary: "Thai culture strongly values honesty and face, and scams are rare outside major tourist hubs.", category: "culture" },
  { name: "Cost of motorbike", summary: "Renting a motorbike in Thailand typically costs 200 to 300 baht a day, and a new one can be bought for around 40,000 baht.", category: "transport" },
  { name: "Fuel prices Thailand", summary: "Fuel in Thailand costs around 30 to 35 baht per liter, with slightly cheaper gasohol blends.", category: "transport" },
  { name: "Thai bus network", summary: "VIP and sleeper buses connect Thai cities cheaply, with overnight trips to Chiang Mai and the south.", category: "transport" },
  { name: "Don Mueang airport", summary: "Don Mueang is Bangkok's budget airport serving low-cost carriers like AirAsia and Nok Air.", category: "travel" },
  { name: "Suvarnabhumi airport", summary: "Suvarnabhumi, Bangkok's main international airport, is one of the busiest hubs in Southeast Asia.", category: "travel" },
  { name: "Thai domestic flights", summary: "Cheap domestic flights make island and northern travel fast, with airlines like AirAsia and Bangkok Airways.", category: "travel" },
  { name: "Thailand 4G 5G", summary: "Thailand has excellent 4G and expanding 5G coverage, even in many rural and island areas.", category: "lifestyle" },
  { name: "Thai e-visa system", summary: "Thailand now issues electronic visas through the official Thai e-Visa portal for many nationalities.", category: "visa" },
  { name: "Visa exemption 60 days", summary: "Many nationalities get 60-day visa exemptions on arrival in Thailand, extendable by 30 days.", category: "visa" },
  { name: "Thailand border bounce", summary: "Some expats historically extended stays by border runs, though rules have tightened in recent years.", category: "visa" },
  { name: "Thai immigration offices", summary: "Thai immigration offices handle extensions and visas, with major offices in Bangkok, Chiang Mai, and Phuket.", category: "visa" },
  { name: "Marriage visa Thailand", summary: "A marriage visa lets expats married to Thai nationals stay a year at a time, renewable annually.", category: "visa" },
  { name: "Thailand education visa", summary: "Education visas allow long stays for language study, and Thailand is popular for learning Thai.", category: "visa" },
  { name: "Retiring in Chiang Mai", summary: "Chiang Mai is a top retirement spot for expats thanks to low costs, cool winters, and good hospitals.", category: "lifestyle" },
  { name: "Expats in Bangkok", summary: "Bangkok hosts the largest expat community in Thailand, concentrated in Sukhumvit and Sathorn.", category: "lifestyle" },
  { name: "Expat communities", summary: "Thailand's expat communities are strong, with Facebook groups, meetups, and clubs in every major city.", category: "lifestyle" },
  { name: "Thai language classes", summary: "Language schools in Bangkok and Chiang Mai offer structured Thai courses for expats.", category: "language" },
  { name: "Thai bribery law", summary: "Corruption is less visible than past decades, and bribery of officials remains illegal in Thailand.", category: "lifestyle" },
  { name: "Thai visa overstay fine", summary: "Overstaying a Thai visa costs 500 baht per day, with longer overstays risking a ban.", category: "visa" },
  { name: "Thai passport power", summary: "The Thai passport is strong regionally, though weaker globally, reflecting visa-free travel agreements.", category: "lifestyle" },
  { name: "Bangkok canals", summary: "Bangkok was once called the Venice of the East for its network of canals, or khlongs.", category: "history" },
  { name: "Chinatown Yaowarat", summary: "Bangkok's Chinatown, Yaowarat, is famous for its street food, gold shops, and Chinese New Year.", category: "travel" },
  { name: "Jim Thompson House", summary: "Jim Thompson's traditional Thai house in Bangkok tells the story of the American silk magnate who vanished.", category: "travel" },
  { name: "Siam Paragon mall", summary: "Siam Paragon is one of Asia's largest malls, with luxury brands, an aquarium, and an opera house.", category: "shopping" },
  { name: "MBK mall bargain", summary: "MBK Center is a Bangkok shopping icon for electronics, phone accessories, and bargains.", category: "shopping" },
  { name: "CentralWorld mall", summary: "CentralWorld is among the world's largest shopping centers, spanning multiple city blocks in Bangkok.", category: "shopping" },
  { name: "Thai air conditioning", summary: "Malls, offices, and buses in Thailand are air-conditioned heavily, so a light jacket helps against the chill.", category: "lifestyle" },
  { name: "Water refill stations", summary: "Many Thais buy water refills at local stations, saving money and plastic compared to bottled water.", category: "lifestyle" },
  { name: "Thai mosquitoes", summary: "Dengue is spread by mosquitoes in Thailand, so repellent and covering up at dusk is wise.", category: "healthcare" },
  { name: "Rabies in Thailand", summary: "Rabies exists in Thailand, and expats should get prompt vaccination after any dog or cat bite.", category: "healthcare" },
  { name: "Thai tap water", summary: "Tap water in Thailand is not safe to drink; expats use filtered or bottled water.", category: "healthcare" },
  { name: "Sun protection", summary: "Thailand's tropical sun is strong, and expats should use sunscreen and stay hydrated year-round.", category: "healthcare" },
  { name: "Thai hospitals English", summary: "Major Thai private hospitals have English-speaking doctors and international patient departments.", category: "healthcare" },
  { name: "Health check up Thailand", summary: "Comprehensive annual health check-ups at Thai private hospitals cost a fraction of Western prices.", category: "healthcare" },
  { name: "Dental care Thailand", summary: "Dental care in Thailand is affordable and high-quality, drawing expats and medical tourists alike.", category: "healthcare" },
  { name: "Thai air quality", summary: "Northern Thailand faces seasonal smog from burning in the dry months, affecting Chiang Mai most.", category: "weather" },
  { name: "Bangkok air quality", summary: "Bangkok's air quality worsens in the dry season with fine dust, prompting mask wearing on bad days.", category: "weather" },
  { name: "Thailand weather now", summary: "Thailand's tropical climate is warm year-round, with average annual temperatures around 27 degrees Celsius.", category: "weather" },
  { name: "Sea temperature Thailand", summary: "Thailand's seas are warm all year, staying around 28 to 30 degrees Celsius in the Gulf.", category: "weather" },
  { name: "Thai constellation name", summary: "The Thai name for Thailand, Prathet Thai, literally means land of the free.", category: "history" },
  { name: "Old name Siam", summary: "Thailand was officially known as Siam until 1939, when the name was changed to Thailand.", category: "history" },
  { name: "Ramkhamhaeng inscription", summary: "The Ramkhamhaeng inscription of 1292 is considered the earliest example of Thai writing.", category: "history" },
  { name: "Ayutthaya kingdom", summary: "The Ayutthaya Kingdom ruled Siam for over 400 years before falling to the Burmese in 1767.", category: "history" },
  { name: "King Mongkut", summary: "King Mongkut, depicted in Anna and the King, modernized Siam and opened it to the West.", category: "history" },
  { name: "Rattanakosin era", summary: "The Rattanakosin era began in 1782 when Bangkok was founded as the Siamese capital.", category: "history" },
  { name: "Thailand 1932 revolution", summary: "A bloodless 1932 revolution changed Thailand from absolute to constitutional monarchy.", category: "history" },
  { name: "Buddhist calendar", summary: "Thailand uses the Buddhist Era calendar, which is 543 years ahead of the Western calendar.", category: "culture" },
  { name: "Thai New Year number", summary: "The current Buddhist year is 2569, used on Thai documents, coins, and government forms.", category: "culture" },
  { name: "Thai zodiac animals", summary: "Thai culture follows the 12-year zodiac animal cycle from the Chinese tradition.", category: "culture" },
  { name: "Water buffalo farming", summary: "Water buffalo still work rice paddies across rural Thailand, though machines are replacing them.", category: "wildlife" },
  { name: "Giant monitor lizards", summary: "Large water monitor lizards, called hia, are commonly seen around Bangkok canals and parks.", category: "wildlife" },
  { name: "Sparrow birds Bangkok", summary: "Tree sparrows and mynas are the most common urban birds in Bangkok's parks.", category: "wildlife" },
  { name: "Koh Samui coconuts", summary: "Koh Samui's coconut groves gave the island its former name, Ko Ram, or coconut island.", category: "travel" },
  { name: "Chao Phraya river", summary: "The Chao Phraya river flows through Bangkok, with express boats serving as commuter transport.", category: "travel" },
  { name: "Bangkok river boat", summary: "The Chao Phraya express boats offer cheap, scenic commutes along Bangkok's river.", category: "transport" },
  { name: "Thai marriage law", summary: "Foreigners can legally marry Thai citizens with local documentation and a statement of freedom to marry.", category: "lifestyle" },
  { name: "Thai inheritance law", summary: "Thailand's inheritance law gives spouses and children rights to estates, with land restrictions for foreigners.", category: "lifestyle" },
  { name: "Condos for foreigners", summary: "Foreigners can own Thai condo units outright as long as under 49% of the building is foreign-owned.", category: "lifestyle" },
  { name: "Land ownership rules", summary: "Foreigners cannot own land in Thailand outright, so many use long leases or Thai partnerships.", category: "lifestyle" },
  { name: "Thai company setup", summary: "Many expats set up Thai companies with Thai partners, keeping foreign ownership under 49%.", category: "lifestyle" },
  { name: "Expat tax Thailand", summary: "Thailand taxes residents on Thai income, and expats should consult advisors on remittance rules.", category: "lifestyle" },
  { name: "Thai retirement cost", summary: "A couple can retire comfortably in Thailand outside Bangkok on 40,000 to 60,000 baht a month.", category: "cost of living" },
  { name: "Phuket cost of living", summary: "Phuket costs more than upcountry Thailand, with rent and dining closer to international levels.", category: "cost of living" },
  { name: "Thailand budget travel", summary: "Budget travelers can get by on about 1,000 baht a day in Thailand with hostels and street food.", category: "cost of living" },
  { name: "Mid-range expat budget", summary: "A mid-range expat lifestyle in Bangkok costs about 60,000 to 90,000 baht a month including rent.", category: "cost of living" },
  { name: "Luxury in Thailand", summary: "Luxury living in Thailand, with serviced apartments and fine dining, can still be far cheaper than Western cities.", category: "cost of living" },
  { name: "Thailand expat visa fees", summary: "Retirement visa extensions cost about 1,900 baht at immigration, plus agent fees if used.", category: "visa" },
  { name: "Thai education cost", summary: "International schools in Bangkok charge 300,000 to 800,000 baht per year in tuition.", category: "cost of living" },
  { name: "Thai private school", summary: "Private bilingual schools in Thailand cost far less than international schools while teaching in English.", category: "cost of living" },
  { name: "Childcare in Thailand", summary: "Nannies and childcare in Thailand are affordable, with live-in nannies often under 15,000 baht a month.", category: "cost of living" },
  { name: "Pet care Thailand", summary: "Vet care in Thailand is inexpensive, and animal clinics are found in every Thai city.", category: "lifestyle" },
  { name: "Golf in Thailand", summary: "Thailand is a golfing destination with over 200 courses, many at world-class resort standards.", category: "lifestyle" },
  { name: "Thai spa culture", summary: "Thai spas offer massages and treatments at a fraction of Western prices, from 300 baht per hour.", category: "lifestyle" },
  { name: "Gym costs Thailand", summary: "Gym memberships in Thailand range from 800 to 2,000 baht a month, with rooftop and boutique options.", category: "lifestyle" },
  { name: "Coworking Bangkok", summary: "Bangkok and Chiang Mai have abundant coworking spaces for remote workers at low daily rates.", category: "lifestyle" },
  { name: "Thai festivals color", summary: "Thai festivals are colorful and frequent, with flower parades, kite festivals, and rocket festivals upcountry.", category: "culture" },
  { name: "Northern lantern festival", summary: "Northern Thailand's Yi Peng festival releases thousands of paper lanterns into the night sky.", category: "culture" },
  { name: "Phuket old town", summary: "Phuket's old town features Sino-Portuguese shophouses and a lively Sunday walking market.", category: "travel" },
  { name: "Kanchanaburi waterfalls", summary: "Kanchanaburi province offers waterfalls, caves, and jungle rivers one to two hours from Bangkok.", category: "travel" },
  { name: "Koh Phangan full moon", summary: "Koh Phangan hosts the famous full moon party on Haad Rin beach each lunar cycle.", category: "travel" },
  { name: "Koh Tao diving school", summary: "Koh Tao is one of the cheapest places in the world to learn scuba diving.", category: "travel" },
  { name: "Thai craft markets", summary: "Thai handicraft markets sell ceramics, lacquerware, silver, and textiles across the north.", category: "shopping" },
  { name: "Benjarong ceramics", summary: "Benjarong is a traditional five-color Thai porcelain craft still produced for collectors.", category: "shopping" },
  { name: "Thai umbrella making", summary: "Bo Sang village near Chiang Mai is famous for hand-painted paper umbrellas.", category: "shopping" },
  { name: "Siam Cats", summary: "The Siamese cat breed, known for its pointed coat, originated in Thailand, once called Siam.", category: "wildlife" },
  { name: "Thai ridgeback dog", summary: "The Thai Ridgeback is a rare native dog breed known for the ridge of hair along its back.", category: "wildlife" },
  { name: "Golden Buddha statue", summary: "Wat Traimit in Bangkok houses the world's largest solid gold Buddha statue, weighing 5.5 tons.", category: "travel" },
  { name: "Reclining Buddha", summary: "Wat Pho's reclining Buddha is 46 meters long and is one of Bangkok's most visited temples.", category: "travel" },
  { name: "Wat Arun temple", summary: "Wat Arun, the Temple of Dawn, is a riverside Bangkok landmark decorated with porcelain.", category: "travel" },
  { name: "Emerald Buddha", summary: "The Emerald Buddha at Wat Phra Kaew, carved from jade, is Thailand's most sacred image.", category: "culture" },
  { name: "Thai puppet theatre", summary: "Thai traditional puppet theatre, hun lakhon lek, is a declining but beautiful art form.", category: "culture" },
  { name: "Thai dance forms", summary: "Classical Thai dance, khon, is masked drama that traditionally told the Ramakien epic.", category: "culture" },
  { name: "Lakhon Thai drama", summary: "Lakhon is graceful Thai classical dance performed at temples and cultural shows.", category: "culture" },
  { name: "Thai classical music", summary: "Thai classical music uses instruments like the ranat xylophone and khim hammered dulcimer.", category: "culture" },
  { name: "Luk thung music", summary: "Luk thung is Thai country music, hugely popular in rural areas with themes of love and rural life.", category: "culture" },
  { name: "Thai soap operas", summary: "Thai lakorn soap operas dominate evening TV with melodramatic love and revenge plots.", category: "culture" },
  { name: "Thai cinema", summary: "Thai cinema gained global fame with films like Ong-Bak and Uncle Boonmee.", category: "culture" },
  { name: "Thai box office", summary: "Thai horror films, including Shutter, are among the most internationally successful Thai movies.", category: "culture" },
  { name: "Thai greeting etiquette", summary: "Return a wai politely in Thailand, with palms at chest level and a slight bow for elders.", category: "culture" },
  { name: "Thai shoes off", summary: "Thais remove shoes before entering homes and temples, a rule every expat learns quickly.", category: "culture" },
  { name: "Thai smiles meaning", summary: "The Thai smile has many meanings, from joy to embarrassment, and reading it takes time.", category: "culture" },
  { name: "Mai pen rai", summary: "Mai pen rai, meaning no worries, captures Thailand's famously relaxed attitude to minor problems.", category: "language" },
  { name: "Thai counting", summary: "Thai numbers use classifier words, so objects are counted with particles like an and tua.", category: "language" },
  { name: "Thai writing system", summary: "Thai script has no spaces between words, using vowels above and below consonants.", category: "language" },
  { name: "Learning Thai fun", summary: "Many expats find Thai approachable once they accept that it is completely different from English.", category: "language" },
  { name: "Bangkok airport code", summary: "Bangkok's two airports are BKK (Suvarnabhumi) and DMK (Don Mueang), far apart in the city.", category: "travel" },
  { name: "Thai visa run costs", summary: "Visa agents in Thailand charge 2,000 to 5,000 baht to arrange extensions and border runs.", category: "visa" },
  { name: "Expat retiree insurance", summary: "Some Thai retirement visas require expats to hold health insurance with local coverage.", category: "visa" },
  { name: "Thai embassy abroad", summary: "Thailand has embassies and consulates in most countries issuing visas and passports.", category: "visa" },
  { name: "Thailand dual citizenship", summary: "Thailand generally does not recognize dual nationality, though citizenship rules are being debated.", category: "lifestyle" },
  { name: "Thai food delivery", summary: "Food delivery apps like Grab and Line Man make eating Thai food effortless for expats.", category: "food" },
  { name: "Bangkok restaurants", summary: "Bangkok's dining scene ranges from Michelin-starred restaurants to legendary street stalls.", category: "food" },
  { name: "Thai coffee shops", summary: "Thailand's cafe culture booms, with specialty roasters in Bangkok and Chiang Mai.", category: "food" },
  { name: "Thai fruit markets", summary: "Thai fruit markets burst with mango, durian, mangosteen, rambutan, and longan by season.", category: "food" },
  { name: "Thai iced coffee", summary: "Thai iced coffee, o-liang, is a strong sweet drink with dark roasted beans and condensed milk.", category: "food" },
  { name: "Thai herbal drinks", summary: "Thai herbal drinks like bael tea and butterfly pea tea are popular health beverages.", category: "food" },
  { name: "Thai street desserts", summary: "Thai street dessert carts sell coconut sweets, crepes, and fried bananas after dark.", category: "food" },
  { name: "Som tam variety", summary: "Som tam comes in regional styles from Isan's spicy papaya salad to Central Thai sweeter versions.", category: "food" },
  { name: "Thai noodle soups", summary: "Boat noodles, kuay teow, and yen ta fo are beloved Thai noodle soups found nationwide.", category: "food" },
  { name: "Thai breakfast", summary: "Thai breakfast often features jok rice porridge, grilled pork, or noodle soup from street stalls.", category: "food" },
  { name: "Vegetarian food Thailand", summary: "Vegetarian Thai food is easy to find, especially in Bangkok with Chinese Buddhist restaurants.", category: "food" },
  { name: "Vegan in Thailand", summary: "Vegan options in Thailand are growing, with many cafes offering plant-based Thai classics.", category: "food" },
  { name: "Gluten-free Thailand", summary: "Gluten-free eating in Thailand requires care since soy sauce and oyster sauce contain wheat.", category: "food" },
  { name: "Halal food Thailand", summary: "Southern Thailand and Bangkok offer excellent halal food, reflecting the Muslim minority.", category: "food" },
  { name: "Thai markets at dawn", summary: "Fresh markets open at dawn in Thailand, when the produce and crowds are at their best.", category: "food" },
  { name: "Durian season", summary: "Durian season peaks between June and August, filling Thai markets with the pungent fruit.", category: "food" },
  { name: "Mango season", summary: "Thai mango season runs March to June, when mango sticky rice is at its sweetest.", category: "food" },
  { name: "Coconut water", summary: "Fresh coconut water from roadside stalls is the classic Thai hydration on hot days.", category: "food" },
  { name: "Thai beer scene", summary: "Craft beer is growing in Thailand despite strict licensing, with breweries in Chiang Mai and Bangkok.", category: "food" },
  { name: "Thai whiskey", summary: "SangSom is Thailand's popular rum-whiskey, usually mixed with soda over ice.", category: "food" },
  { name: "Thai nightlife", summary: "Thai nightlife ranges from chic rooftop bars in Bangkok to beach parties in Phuket and Samui.", category: "lifestyle" },
  { name: "Thai beach clubs", summary: "Beach clubs on Samui, Phuket, and Pattaya offer daybeds, music, and sunset cocktails.", category: "lifestyle" },
  { name: "Muay Thai training camps", summary: "Muay Thai camps across Thailand train beginners and pros alike for low monthly fees.", category: "lifestyle" },
  { name: "Thai yoga retreats", summary: "Thailand's islands and mountains host yoga and wellness retreats popular with expats.", category: "lifestyle" },
  { name: "Thai golf courses", summary: "Courses like Red Mountain in Phuket rank among Asia's most scenic golf layouts.", category: "lifestyle" },
  { name: "Bangkok parks", summary: "Lumpini Park is Bangkok's green heart, with joggers, tai chi, and monitor lizards.", category: "lifestyle" },
  { name: "Cycling in Thailand", summary: "Cycling is growing in Thailand with organized rides and bike-friendly paths in the north.", category: "lifestyle" },
  { name: "Trail running", summary: "Trail running events in Doi Inthanon and Khao Yai attract runners from around the world.", category: "lifestyle" },
  { name: "Thai weekends markets", summary: "Weekend markets in Thailand are social hubs where families eat, shop, and relax together.", category: "shopping" },
  { name: "Antiques in Thailand", summary: "Antique shops in Bangkok sell Thai and regional art, though export rules require permits.", category: "shopping" },
  { name: "Tailor shops Bangkok", summary: "Bangkok tailor shops make custom suits and shirts within days at bargain prices.", category: "shopping" },
  { name: "Thai jewelry", summary: "Thailand is a major gem and jewelry exporter, with markets in Bangkok and Chanthaburi.", category: "shopping" },
  { name: "Thai spa products", summary: "Thai spa products like lemongrass oil and herbal balms make popular gifts.", category: "shopping" },
  { name: "Souvenirs from Thailand", summary: "Top Thai souvenirs include silk, ceramics, spices, tea, and handcrafted homewares.", category: "shopping" },
  { name: "Thai package shipping", summary: "Shipping from Thailand is reliable via Thai Post, used by expats sending goods home.", category: "lifestyle" },
  { name: "Thai business hours", summary: "Many Thai shops open by 10am and stay open past 9pm, while malls close around 10pm.", category: "lifestyle" },
  { name: "Bangkok water taxis", summary: "Khlong boats in Bangkok dodge traffic along canal routes at rush hour for commuters.", category: "transport" },
  { name: "Thai rail overnight", summary: "Overnight sleeper trains from Bangkok to Chiang Mai offer bunk beds and a dining car.", category: "transport" },
  { name: "Thai domestic budget", summary: "Budget airlines like AirAsia connect Thai cities for often under 1,500 baht one way.", category: "transport" },
  { name: "Metered taxis Bangkok", summary: "Metered taxis in Bangkok start at 35 baht, making them cheap versus many world cities.", category: "transport" },
  { name: "Thai traffic rules", summary: "Thai roads have heavy motorbike traffic, and expats should wear helmets and ride defensively.", category: "transport" },
  { name: "Thai license plates", summary: "White plates are private cars in Thailand, while green plates are commercial vehicles.", category: "transport" },
  { name: "Taxi apps Thailand", summary: "Besides Grab, Thai apps like Bolt and inDrive offer cheaper rides in Bangkok.", category: "transport" },
  { name: "Car ownership Thailand", summary: "Cars in Thailand are common and affordable to run, with cheap parts and service.", category: "transport" },
  { name: "Motorbike parking", summary: "Motorbikes park for free on sidewalks in Thailand, while cars use paid lots.", category: "transport" },
  { name: "Thai highway tolls", summary: "Bangkok's expressways charge tolls of about 30 to 70 baht per section.", category: "transport" },
  { name: "Thai train safety", summary: "Thailand's train network is slow but safe, with panoramic routes along the southern coast.", category: "transport" },
  { name: "Speed boats islands", summary: "Speed boats cut ferry times to Thai islands dramatically but are bumpier in rough seas.", category: "transport" },
  { name: "Thai immigration queue", summary: "Immigration queues at Bangkok airports can be long, so frequent fliers use fast-track services.", category: "visa" },
  { name: "Thai visa photographs", summary: "Thai visa applications require white-background photos, available cheaply at photo shops.", category: "visa" },
  { name: "Expat mail forwarding", summary: "Expats use mail forwarding services in Thailand to manage post and packages.", category: "lifestyle" },
  { name: "Thai laundry services", summary: "Laundry services in Thailand charge around 20 to 30 baht per kilogram across the country.", category: "lifestyle" },
  { name: "Maid services Thailand", summary: "Monthly maid services in Thailand cost roughly 2,000 to 4,000 baht in major cities.", category: "lifestyle" },
  { name: "Thai barber prices", summary: "A haircut in Thailand typically costs 100 to 200 baht at local barbershops.", category: "lifestyle" },
  { name: "Thai coffee prices", summary: "Local Thai coffee costs about 40 to 60 baht, while specialty cafe lattes run 100 to 160 baht.", category: "cost of living" },
  { name: "Thai cinema prices", summary: "Cinema tickets in Thailand cost 150 to 300 baht, with discounted early shows.", category: "cost of living" },
  { name: "Gym class prices", summary: "Group fitness classes in Thailand cost 200 to 400 baht per session in cities.", category: "cost of living" },
  { name: "Thai concert culture", summary: "Live music and concerts thrive in Bangkok, from small jazz bars to arena tours.", category: "culture" },
  { name: "Thai wedding traditions", summary: "Thai weddings blend Buddhist ceremonies, water blessings, and shared family meals.", category: "culture" },
  { name: "Songkran family time", summary: "Songkran is also a family reunion holiday when Thais travel home to clean houses and honor elders.", category: "culture" },
  { name: "Thai merit making", summary: "Thais make merit at temples with donations, food offerings, and releasing captive birds.", category: "culture" },
  { name: "Lotus flowers", summary: "Lotus flowers are offered at Thai temples and used in Buddhist ceremonies.", category: "culture" },
  { name: "Thai incense", summary: "Incense at Thai temples comes in bundles of three, representing the Buddha, Dharma, and Sangha.", category: "culture" },
  { name: "Thai spirit houses", summary: "Many Thai homes and businesses keep spirit houses to shelter local guardian spirits.", category: "culture" },
  { name: "Thai superstitions", summary: "Thai superstitions range from lucky numbers to keeping scissors away at night.", category: "culture" },
  { name: "Red threads Thailand", summary: "Red threads and talismans are worn by many Thais for protection and luck.", category: "culture" },
  { name: "Thai name meanings", summary: "Thai names often carry meanings like good, beautiful, or victorious, chosen with care.", category: "culture" },
  { name: "Thai married names", summary: "Thai women traditionally take their husband's surname, though many keep their own professionally.", category: "culture" },
  { name: "Thai address system", summary: "Thai addresses use district and province names, with sub-districts, and are often cryptic to visitors.", category: "lifestyle" },
  { name: "Thai phone numbers", summary: "Thai mobile numbers start with 08 or 09, and the country code is +66.", category: "lifestyle" },
  { name: "Thai postal codes", summary: "Thai postal codes are five digits, beginning with region numbers like 10 for Bangkok.", category: "lifestyle" },
  { name: "Thai emergency services", summary: "In Thailand, call 1669 for an ambulance and 199 for fire, alongside 191 for police.", category: "lifestyle" },
  { name: "Tourist police", summary: "Tourist police in Thailand speak English and help with travel issues at hotline 1155.", category: "lifestyle" },
  { name: "Thai hospital English", summary: "Emergency departments at Bangkok private hospitals have on-call English translators.", category: "healthcare" },
  { name: "Thai vaccination clinics", summary: "Vaccination clinics in Thailand offer flu, rabies, and travel shots at low prices.", category: "healthcare" },
  { name: "Dental clinics Bangkok", summary: "Dental clinics in Bangkok offer whitening and implants at a third of Western prices.", category: "healthcare" },
  { name: "Eye care Thailand", summary: "Thailand's eye hospitals attract medical tourists for LASIK and cataract surgery.", category: "healthcare" },
  { name: "Thai pharmacies brands", summary: "Bangkok pharmacy chains like Boots and Watsons are found in every mall.", category: "healthcare" },
  { name: "Skin clinics Thailand", summary: "Thai skin and cosmetic clinics are abundant in Bangkok, offering affordable treatments.", category: "healthcare" },
  { name: "Thai herbal medicine", summary: "Thai herbal medicine uses turmeric, lemongrass, and plai root for healing traditions.", category: "healthcare" },
  { name: "Thai gym culture", summary: "Gym culture is booming in Thai cities, with modern 24-hour fitness chains in malls.", category: "lifestyle" },
  { name: "Thai run clubs", summary: "Running clubs meet in Bangkok parks and Chiang Mai mornings for group jogs.", category: "lifestyle" },
  { name: "Thai beach volleyball", summary: "Beach volleyball is popular on Thai beaches with courts at Hua Hin and Pattaya.", category: "lifestyle" },
  { name: "Paddle boarding Thailand", summary: "Stand-up paddle boarding is a growing activity on Thai bays and lakes.", category: "lifestyle" },
  { name: "Thai boat trips", summary: "Island-hopping boat tours cost 500 to 1,500 baht from Thai beach towns.", category: "travel" },
  { name: "Snorkeling Thailand", summary: "Snorkeling trips to coral reefs are a must-do around Koh Tao, Similan, and the Andaman islands.", category: "travel" },
  { name: "Thai sunset spots", summary: "Famous Thai sunsets glow over Phuket's beaches and the Cha Am coast.", category: "travel" },
  { name: "Khao Yai wineries", summary: "Khao Yai's cool hills are home to Thai wineries producing local varietals.", category: "travel" },
  { name: "Coffee farms Doi Chang", summary: "Doi Chang and other northern hills host arabica coffee farms open to visitors.", category: "travel" },
  { name: "Elephant sanctuaries", summary: "Ethical elephant sanctuaries in Chiang Mai and Phuket let visitors feed and bathe rescued elephants.", category: "wildlife" },
  { name: "Monkey island Thailand", summary: "Monkey islands like Koh Mook and Koram attract tourists feeding cheeky macaques.", category: "wildlife" },
  { name: "Coral bleaching", summary: "Coral bleaching has affected Thai reefs, prompting conservation efforts in marine parks.", category: "wildlife" },
  { name: "Jellyfish Thailand", summary: "Jellyfish appear in some Thai waters seasonally; beaches with warnings post flags.", category: "wildlife" },
  { name: "Thai sea gypsies", summary: "The Moken, or sea gypsies, live along Thailand's Andaman coast and islands.", category: "culture" },
  { name: "Thai hill tribes", summary: "Thailand's northern hill tribes, including Hmong and Karen, maintain distinct traditions.", category: "culture" },
  { name: "Thai Muslim south", summary: "Thailand's deep south has a Malay Muslim majority with its own culture and food.", category: "culture" },
  { name: "Chinese Thai community", summary: "Thailand's ethnic Chinese community deeply shapes business, food, and festivals.", category: "culture" },
  { name: "Thai minority languages", summary: "Thailand has dozens of minority languages beyond Thai, including Lao, Karen, and Malay.", category: "language" },
  { name: "English in Thailand", summary: "English proficiency in Thailand is growing but limited outside tourist areas.", category: "language" },
  { name: "Thai city names", summary: "Thai city names often mean victories or cities, like Chiang Mai meaning new city.", category: "language" },
  { name: "Thai transliteration", summary: "Thai romanization is inconsistent, so names like Bangkok and Krung Thep both appear.", category: "language" },
  { name: "Bangkok long name", summary: "Bangkok's ceremonial name is the longest city name in the world, over 150 characters long.", category: "culture" },
  { name: "Thai mangosteen season", summary: "Mangosteen season peaks from May to September in southern Thailand.", category: "food" },
  { name: "Lychee season Thailand", summary: "Lychees from northern Thailand are prized each May and June.", category: "food" },
  { name: "Thai longan fruit", summary: "Longan, known as lam yai, is a sweet lychee relative grown in the north.", category: "food" },
  { name: "Thai pomelo", summary: "Thai pomelo, the giant citrus, is served in salads and eaten fresh with chili salt.", category: "food" },
  { name: "Thai snake fruit", summary: "Salak, snake fruit, is a scaly, sweet tropical fruit sold in Thai markets.", category: "food" },
  { name: "Thai sugar palm", summary: "Sugar palm syrup sweetens many Thai desserts and drinks.", category: "food" },
  { name: "Thai jasmine rice", summary: "Thai hom mali jasmine rice is among the world's most fragrant rice varieties.", category: "food" },
  { name: "Thai fish sauce", summary: "Nam pla fish sauce is the salty backbone of nearly every Thai dish.", category: "food" },
  { name: "Thai chili paste", summary: "Nam prik chili pastes are eaten with vegetables and fish across Thai homes.", category: "food" },
  { name: "Thai curry pastes", summary: "Thai curries are built on freshly pounded pastes of chilies, galangal, and lemongrass.", category: "food" },
  { name: "Coconut milk cooking", summary: "Coconut milk thickens and sweetens Thai curries and desserts alike.", category: "food" },
  { name: "Thai herbs and spices", summary: "Thai cooking leans on lemongrass, kaffir lime, galangal, and Thai basil for freshness.", category: "food" },
  { name: "Thai table setting", summary: "Thai meals are shared family style, with several dishes, rice, and a central soup.", category: "food" },
  { name: "Eating Thai style", summary: "Thais eat with a spoon and fork, reserving chopsticks for noodle dishes.", category: "food" },
  { name: "Thai food mild request", summary: "Ordering mai phet requests mild Thai food, while phet mak means very spicy.", category: "food" },
  { name: "Thai street hygiene", summary: "Busy Thai street stalls are generally safe, and locals judge stalls by queue length.", category: "food" },
  { name: "Michelin Bangkok", summary: "Bangkok was the first city to award Michelin stars to street food vendors.", category: "food" },
  { name: "Jay Fai street chef", summary: "Jay Fai, Bangkok's crab omelette street chef, became the first street vendor to win a Michelin star.", category: "food" },
  { name: "Thai roti stalls", summary: "Muslim roti stalls in Thai cities serve sweet roti with banana and condensed milk.", category: "food" },
  { name: "Thai ice cream carts", summary: "Ice cream carts and tubtim grob red rubies drinks are classic Thai street treats.", category: "food" },
  { name: "Thai energy drinks", summary: "Thai energy drinks like M-150 and Krating Daeng are popular with workers.", category: "food" },
  { name: "Thai iced tea shops", summary: "Specialty Thai iced tea shops have opened across Bangkok with fancy toppings.", category: "food" },
  { name: "Coconut ice cream", summary: "Coconut ice cream served in a coconut shell is a favorite Thai dessert.", category: "food" },
  { name: "Thai breakfast markets", summary: "Morning markets in Thailand serve rice porridge, dim sum, and grilled meat for breakfast.", category: "food" },
];

async function main() {
  const items = DATA.slice(0, 100);
  let inserted = 0;
  for (const item of items) {
    const embedRes = await fetch(`${BASE}/api/embed`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ texts: [item.summary] }),
    });
    const embedData = await embedRes.json();
    if (!embedRes.ok) throw new Error(embedData.error);

    const res = await fetch(`${BASE}/api/vectors`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...item, embedding: embedData.embeddings[0] }),
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error);
    inserted++;
    if (inserted % 20 === 0) console.log(`inserted ${inserted}/${items.length}`);
  }
  console.log(`Done. Inserted ${inserted} items.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
